<a href="https://colab.research.google.com/github/MadhuriMapari/MadhuriMapari/blob/main/Basics_of_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch 

# Basics of PyTorch

In [2]:
t1 = torch.tensor(4.)
t1

tensor(4.)

`4.` is shorthand for `4.0`. it is used to indicate to Python( and PyTorch) that create a floating -point number. to verify this ,check the `dtype` attribute of tensor

In [3]:
t1.dtype

torch.float32

Lets try some more complex tensor 

In [4]:
t2 = torch.tensor((1.,2,3,4))
t2

tensor([1., 2., 3., 4.])

So all the elements of tensor have same datatype

In [5]:
t2.dtype

torch.float32

In [6]:
#Matrix: 2 dimensional  
t3 = torch.tensor([[5.,6],
                   [7,8],
                   [9,10]])
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [7]:
#3 dimensional array
t4 = torch.tensor([
                   [[11,12,13],
                    [13,14,15]],
                   [[15,16,17],
                     [17,18,19.]]])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

Tensor can have any number of dimensions and different lengths along each dimension. We can inspect the length along each diamension using the `.shape` property of a tensor

In [8]:
print(t1)
t1.shape

tensor(4.)


torch.Size([])

In [9]:
print(t2)
t2.shape

tensor([1., 2., 3., 4.])


torch.Size([4])

In [10]:
print(t3)
t3.shape

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])


torch.Size([3, 2])

In [11]:
print(t4)
t4.shape

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])


torch.Size([2, 2, 3])

**Note**: its not possible to create tensor with an improper shape.

In [12]:
t5 = torch.tensor([[5.,6,11],
                   [7,8],
                   [9,10]])
t5

ValueError: ignored

### Tensor Operations and Gradients

Combine tensors with the usual arithmetic operations. 


In [13]:
x = torch.tensor(3.)
w = torch.tensor(4.,requires_grad=True)
b = torch.tensor(5.,requires_grad=True)
x,w,b 

(tensor(3.), tensor(4., requires_grad=True), tensor(5., requires_grad=True))

Combine three tensors: `x`,`w`, and `b`, all numbers.`w` and `b` have an additional parameter `requires_grad` set to `True`. 

Let's create a new tensor `y` by combining these tensors 

In [14]:
y = w * x + b 
y

tensor(17., grad_fn=<AddBackward0>)

As expected, y is a tensor with the value `3 * 4 + 5 = 17`. 

What makes pytorch unique is that we can automatically compute the derivative of `y` w.r.t. the tensors that have `requires_grad` set to `True`  i.e. `w`,`b`. This feature of Pytorach is called **autograd** (automatic gradients).

To compute the derivatives, we can invoke the `.backward` method on our result 

In [15]:
#Compute Derivatives
y.backward()

Deritives of `y` w.r.t the input tensors are stored in the `.grad` property of the respective tensors 

In [16]:
# Display gradients 
print('dy/dx:',x.grad)
print('dy/dw:',w.grad)
print('dy/db:',b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


As expected, dy/dw has the same value as `x` i.e., `3`, and `dy/db` has the value `1`. 

Note that `x.grad` is `None` because `x` doesn't have `requires_grad` set to `True`.

The "grad" in `w.grad` is short for *gradient*, which is another term for derivative. The term *gradient* is primarily used while dealing with vectors and matrices. 

### Tensor Functions
Apart from arithmetic operations,the `torch` module also containsmany fuctions for creating and manipulating tensors.

In [17]:
#Create a tensor with a fixed value for every element
t6 = torch.full((3,2),42)
t6

tensor([[42, 42],
        [42, 42],
        [42, 42]])

In [ ]:
# Concatenate two tensors with compatible shapes
t7 = torch.cat((t3,t6))
t7

In [19]:
# Compute the sin of each element
t8 = torch.sin(t7)
t8

tensor([[-0.9589, -0.2794],
        [ 0.6570,  0.9894],
        [ 0.4121, -0.5440],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165],
        [-0.9165, -0.9165]])

In [20]:
t8.shape

torch.Size([6, 2])

In [21]:
# Change theshape of a tensor
t9 =t8.reshape(3,2,2)
t9

tensor([[[-0.9589, -0.2794],
         [ 0.6570,  0.9894]],

        [[ 0.4121, -0.5440],
         [-0.9165, -0.9165]],

        [[-0.9165, -0.9165],
         [-0.9165, -0.9165]]])

### Interoperability with Numpy 

In [22]:
import numpy as np

#create an array in Numpy  
x = np.array([[1,2],
              [3,4.]])
x

array([[1., 2.],
       [3., 4.]])

We can convert a numpy array to a torch tensor.

In [23]:
# Convery the numpy array to a torch tensor
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [24]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

similarly we can convert tensor to numpy array 

In [25]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

Interoperability between pytorch and Numpy is essential because data will be read and preprocessed as numpy 

**Why tensor instead of numpy?**

Numpy provides data structures and utilities for working with multi-dimensional numeric data. However Pytorch is used for below two reasons
1. **Autograd**: The ability to automatically compute graditents for tensor operations is essential for training deep learning models.
2. **GPU support**: While working with massive datasets and large models, Pytorch tensor operations can be efficiently performed using Graphical Processing Unit(GPU).Computation that might typically take hours can be completed within minutes using GPUs.



## Gradient Descent and Linear Regression

### Introduction of Linear Regression:

In Linear Regression model, each target variable is estimated to be weighted sum of input variables, offset by some constant known as a bias.

The *learning* part of linear regression is to figure out a set of weights `w11,w12,...` and biases `b1,b2,...` using the training data, to make accurate predictions for new data.  


